spring:
  application:
    name: blogs
  api-docs:
    path: /api-docs
  main:
    allow-circular-references: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/blogs_db"
    platform: postgresql
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        format_sql: false
        jdbc:
          batch_size: 20000
          lob:
            non_contextual_creation: true
