name: Build & Deploy Blog App

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Blog Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build Application
        run: |
          mvn clean
          mvn -B package --file pom.xml