name: Build & Deploy Blog App

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Blog Application
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: blogs_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run migrations
        run: psql -f sql/migration.sql postgresql://postgres:password@localhost:5432/blogs_db

      - name: Unit Tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: mvn -B test --file pom.xml

      - name: Build Application
        run: |
          mvn clean
          mvn -B package --file pom.xml